project:
  type: website

website:
  title: "Random musings"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/jvkersch
      - icon: twitter
        href: https://twitter.com/jvkersch

format:
  html:
    theme: litera
    css: styles.css

execute:
  freeze: auto
